# Generated by Django 3.0.5 on 2020-05-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
    ]
